name: Build Desktop App

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          
      - name: Install and Build Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build
          
      - name: Install and Build Backend
        working-directory: ./backend
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
          python build.py
          
      - name: Install and Build Electron App
        working-directory: ./desktop
        run: |
          npm ci
          npm run dist
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: brainweb-desktop-${{ matrix.os }}
          path: desktop/dist/*.exe
          if-no-files-found: ignore
          
      - name: Upload Mac Artifacts
        uses: actions/upload-artifact@v7
        if: matrix.os == 'macos-latest'
        with:
          name: brainweb-desktop-mac
          path: desktop/dist/*.dmg
          
      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v7
        if: matrix.os == 'ubuntu-latest'
        with:
          name: brainweb-desktop-linux
          path: desktop/dist/*.AppImage
